apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "hotel-booking"
  namespace: tolu
spec:
  cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: tensorflow
            # modify this property if you would like to use a custom image
            image: mavencodev/tf_hotel:v.0.1 # put the correct image
            command:
                - "python"
                - "/tfjob-hotel-demand.py"
                - "--batch_size=64"
                - "--learning_rate=0.1"
                - "--optimizer=adam"
